-- Reconcile series with the real calendar.
--
-- A recurring meeting already exists twice in this app: as a cp_series (hand
-- made, holds the standing agenda and the instance history) and as the actual
-- calendar event in placed_blocks, which Today's ical ingest writes and the
-- Agenda screen reads. Opening the meeting from the Agenda launched the
-- composer with only a title, so the saved note never joined its series.
--
-- calendar_titles holds the placed_blocks title(s) this series owns. It's an
-- array because calendar names drift ("Jon 1:1" / "Jon / Nate 1:1") and one
-- series can legitimately cover more than one recurring block.
--
-- Titles, not block ids: placed_blocks rows are regenerated by Today, so ids
-- are not stable. cp_tasks.meeting_id already stores the title for the same
-- reason, which makes the title the one join key all three surfaces share.

alter table public.cp_series
  add column if not exists calendar_titles text[] not null default '{}';
